### ISSUE TITLE
Direct access to lectures

### ISSUE THREAD

**Issue by stuntguy3000** [SwadicalRag/flinders-tools#1]
Having a way to open lectures in another tab (direct link) would be nice.

**Comment by SwadicalRag** [comment]
When I rewrote the lecture viewer, I was experimenting with react for the very first time and did clientside routing horribly with another library which didn't interoperate with react by itself.

I'd probably have to edit the codebase to use `react-router` instead before implementing this. And it would be great if I used another library like Redux to manage the state in this single page app.

I'm pretty busy with semester 2 stuff atm; no promises, but this is something I want to do in the near future.

**Comment by stuntguy3000** [comment]
Sounds good.

**Comment by SwadicalRag** [comment]
done

**Comment by stuntguy3000** [comment]
Appreciated fam.

**Comment by SwadicalRag** [comment]
👌
