### ISSUE TITLE
Topic ENGR2881 Missing

### ISSUE THREAD

**Issue by stuntguy3000** [SwadicalRag/flinders-tools#14]
As title says, one of my topics ENGR2881 is missing. It's in the Unibuddy API, but I can see that fetch call is commented out so... 🤷‍♂️

**Comment by SwadicalRag** [comment]
good spot! I commented out the fetch call because I figured that it would hammer the unibuddy API too much when I could just cache it (as a static json file) in this repo and let cloudflare/github handle it

I've just updated the topic list in 0d913df

**Comment by SwadicalRag** [comment]
also apologies for the delay, I've only just been able to sit down and look through my emails

**Comment by stuntguy3000** [comment]
All good mate, we all appreciate your upkeep of this amazing tool 👏
