### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by lin0287** [SwadicalRag/flinders-tools#15]
Infinite loading screen when viewing lectures.

**Comment by SwadicalRag** [comment]
I am still able to access videos via the lecture viewer. This is likely an issue to do with Flinders' `video.flinders.edu.au` server and not the viewer itself. There are many reasons for a lecture to be listed but not have a valid video stream URL.

**Comment by SwadicalRag** [comment]
The red flags I'd be looking out for are: (in order of priority)
1. `flinders.tools` is not even loading
2. No videos are working across multiple topics
3. A topic that used to have a list of lectures is now completely empty

Anything else is probably out of my hands, and would be very time consuming to look into.

If any of those things are happening to you, please feel free to re-open the issue
