### ISSUE TITLE
Topic Selection has duplicate items

### ISSUE THREAD

**Issue by stuntguy3000** [SwadicalRag/flinders-tools#6]
![image](https://cloud.githubusercontent.com/assets/1522389/17993355/44f05354-6b8e-11e6-89a9-400c27eaae30.png)

Loving the work/new domain so far btw.

I believe this has something to do with multiple years or something funky along those lines. Never used react so I have no idea how any of it works.

Either a filter, or year display would be neat.

**Comment by SwadicalRag** [comment]
it actually has to do with the same subject being registered under Semester 1, Semester 2, and Distance Education

I'll have to go through the json data and remove duplicate entries later

**Comment by stuntguy3000** [comment]
I see, interesting.

**Comment by SwadicalRag** [comment]
done

https://github.com/SwadicalRag/flinders-tools/blob/gh-pages/js/src/components/modal.lectureaddition.tsx#L9-L35
