### ISSUE TITLE
Dialogue box CSS mismatch

### ISSUE THREAD

**Issue by stuntguy3000** [SwadicalRag/flinders-tools#7]
![image](https://cloud.githubusercontent.com/assets/1522389/17993422/ce157b64-6b8e-11e6-9f13-490af25f573b.png)

Just noticed this in Fullscreen, but testing with mobile support shows it correctly nested within the title bar.

**Comment by SwadicalRag** [comment]
seems like a semantic UI problem

this is why i hate web dev

i probably won't fix this, since it doesn't impair the functionality of the selector

**Comment by stuntguy3000** [comment]
No worries
